
name: Build LaTeX PDF on Release


on:
  release:
    types: [created]


jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Rename PDF
        run: mv main.pdf ITAT-Formelsammlung.pdf

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ITAT-Formelsammlung.pdf
          asset_name: ITAT-Formelsammlung.pdf
          asset_content_type: application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
